---
- name: Pull and Run docker image of shivraj25/bidding_app_springboot
  hosts: all
  tasks:
    - name: Pull shivraj25/bidding_app_springboot
      docker_image:
        name: shivraj25/bidding_app_springboot
        source: pull

    - name: Create default containers
      docker_container:
        name: c1
        image: shivraj25/bidding_app_springboot
        state: present

- name: Running MYSQL Database as Docker Container using Ansible.
  hosts: all

  vars:
    db_volume: db_data

  tasks:
    - name: Launch mysql database container
      docker_container:
        name: mysql-standalone-01
        image: mysql:5.7
        volumes:
          - "{{ db_volume }}:/var/lib/mysql"
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: Shivraj@25
          MYSQL_DATABASE: bidding_app_db
          MYSQL_USER: Shivraj
          MYSQL_PASSWORD: Shivraj@25
        ports:
          - "3307:3306"
